### ISSUE TITLE
New template based in latex for cheatsheet 

### ISSUE THREAD

**Issue by ambarja** [ambarja/cheatsheet-qgisprocess#3]
Hi @florisvdh, I've added new cheasheet template based on latex, I've been thinking that it's better to have a code based version for possible future changes and also quick to update.
Here is the final result in pdf or png format.
The size is based on Posit - Cheasheet requirements, I think that when the package is in CRAN this cheasheet should also be in posit.
What do you think?
[qgisprocess.pdf](https://github.com/ambarja/cheatsheet-qgisprocess/files/11855525/qgisprocess.pdf)
<br>
![qgisprocess_en](https://github.com/ambarja/cheatsheet-qgisprocess/assets/23284899/7cb46b6f-b104-4b71-95e6-444da114de31)

**Comment by florisvdh** [comment]
Nice @ambarja, I look forward to this approach! Good that you align with Posit and that we have a programmed interface now! Much easier to review and collaborate on.

I posted a few minor suggestions in a21c9df.

**Comment by ambarja** [comment]
Hi @florisvdh I have recently modified some suggested views.
Please could you review the modified suggestions?  
When this is 100% finished, I will create again a new cheasheet in spanish with the same format.

- [New cheasheet in english](https://github.com/ambarja/cheatsheet-qgisprocess/blob/main/pdf/english/qgisprocess_en.pdf)

**Comment by ambarja** [comment]
@florisvdh  maybe I have seen the last commit in qgisprocess repository and there are new functions, also I thinking in create two cheasheet in my free times.
Do you think it is necessary to have two cheatsheets?

**Comment by florisvdh** [comment]
Hi @ambarja you're totally free to keep the Spanish one up to date. Necessary? No, don't feel obliged. Added value? Absolutely, you're welcome to add the translation! The current mention of the Spanish not being up to date, is, as far as I'm concerned, just temporarily until you have added an update (since I wasn't sure how fast you'd be with that). That being said, don't feel obliged: choice of maintaining Spanish version or not (hence removing), is totally yours.

I will review a little later (hope tomorrow), now being tired from travelling to FOSS4G (which starts).

**Comment by ambarja** [comment]
Ohhh you're welcome @florisvdh , at the moment both are up to date, rather successful in the foss4g 🚀 .

**Comment by florisvdh** [comment]
Great, thanks!

Two remaining notes:

- Mission: the text comes too close to the next title 'Features'. This could be solved easily by dropping the text that refers to RQGIS/RQGIS3, that is not needed in a cheatsheet (referring to these packages is done at the homepage already).
- Pipe integration: better move `st_as_sf() |>` to its own line.

**Comment by florisvdh** [comment]
Hi @ambarja can you still handle the above two notes, as well as the comment in https://github.com/r-spatial/qgisprocess/issues/166#issue-1799074588 by @tylerbhampton notably: _the topographic wetness index is TWI not TPI_ ?

**Comment by ambarja** [comment]
Hi @florisvdh Of course, In this week I try edit and modify the final version of cheatsheet :3
